on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true
env:
  DATABASE_USER: "postgres"
  DATABASE_NAME: "postgres"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-musl
      - uses: goto-bus-stop/setup-zig@v2
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: sqlx-cli
      - run: |
          cargo sqlx migrate run
          cargo sqlx prepare --workspace
        env:
          DATABASE_URL: postgres://${{ env.DATABASE_USER }}@localhost:5432/${{ env.DATABASE_NAME }}?sslmode=disable
      - run: |
          cargo build --release
